package com.chemecador.secretaria.core

object Constants {
    const val USERS = "users"
    const val USERCODE = "usercode"
    const val USERCODES = "usercodes"
    const val COUNTER = "counter"
    const val DATE = "date"
    const val NOTES_LIST = "noteslist"
    const val NOTES = "notes"
    const val FRIENDSHIPS = "friendships"
    const val CONTRIBUTORS = "contributors"
    const val SENDER_ID = "senderId"
    const val RECEIVER_ID = "receiverId"
    const val RECEIVER_CODE = "receiverCode"
    const val SENDER_NAME = "senderName"
    const val RECEIVER_NAME = "receiverName"
    const val ACCEPTANCE_DATE = "acceptanceDate"
    const val REQUEST_DATE = "requestDate"
    const val LIST_ID = "listId"
    const val LIST_NAME = "listName"
    const val NOTE_ID = "noteId"
    const val ABOUT_US = "about_us"
    const val SETTINGS = "settings"
    const val FRIENDS = "friends"
}
